name: rtorrent-graphql
description: A HTTP Graphql server to query a rTorrent server
author: Guillaume Desforges <guillaume.desforges.pro@gmail.com>

dependencies:
  - base
  - bytestring
  - morpheus-graphql
  - text

library:
  source-dirs: ./src/lib

executable:
  source-dirs: ./src/exe
  main: Main
  dependencies:
    - rtorrent-graphql
    - scotty

tests:
  tasty:
    source-dirs: ./src/test
    main: Tests
    dependencies:
      - rtorrent-graphql
      - HUnit
      - scotty
      - tasty
      - tasty-hunit
      - http-test
